name: Docker Image CI for GHCR

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ dotfiles_update_rebuild ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the Image
        run: |
          echo ${{ secrets.GH_PAT }} | docker login --username cjn4825 \
          --password-stdin ghcr.io
          docker build --no-cache -t ghcr.io/cjn4825/dev:latest .
          docker push ghcr.io/cjn4825/dev:latest
